angular.module(
    'de.cismet.custom.directives',
    [
        'easypiechart',
        'de.cismet.custom.services',
        'eu.crismaproject.worldstateAnalysis.services',
        'mgcrea.ngStrap.modal',
        'mgo-angular-wizard',
        'mgcrea.ngStrap.button',
        'mgcrea.ngStrap.select',
        'ngSanitize'
    ]
);